version: "3.8"

services:
  server:
    build:
      context: ./server
      target: builder
    image: server
    ports:
      - "50052:50052"
  db:
    image: postgres
    volumes:
      - .data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres