version: "3.8"

services:
  server:
    build: shorturl-server
    image: shorturl-server
    ports:
      - "50052:50052"
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    volumes:
      - .data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres


